import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { chromium, request, expect } from '@playwright/test';
import postgres from 'postgres';
import { setAdministrator } from '../../scripts/admin/account.mjs';
assert.equal(process.env.AUTH_TEST_ISOLATED, 'true');
assert.match(new URL(process.env.DATABASE_URL).pathname, /^\/jiuheng_test_[a-f0-9]+$/);
const sql = postgres(process.env.DATABASE_URL, { onnotice: () => {} });
const baseURL = process.env.SITE_URL, headers = { Origin: baseURL };
const a = await request.newContext({ baseURL }), b = await request.newContext({ baseURL }), anon = await request.newContext({ baseURL });
const username = 'test-owner', short = 'a', spaced = ` ${randomBytes(12).toString('hex')} `;
const checks = [];
const login = (client, password, account = username, extra = {}) => client.post('/api/admin/login', { headers: { ...headers, ...extra }, data: { username: account, password } });
async function status(response, expected, label) { assert.equal(response.status(), expected, label); checks.push(label); }
async function denied(client) { await status(await client.post('/api/admin/posts', { headers }), 401, 'Revoked session cannot write'); }
let browser;
try {
  await status(await a.post('/api/admin/setup', { headers, data: { username, password: short } }), 404, 'No web registration even before setup');
  await status(await a.get('/admin/setup'), 404, 'Setup page removed');
  await assert.rejects(setAdministrator(sql, username, ''), /密码为空/); checks.push('CLI initializer rejects empty password');
  await setAdministrator(sql, username, short);
  await status(await login(a, short), 200, 'Single-character initial password accepted');
  await status(await login(b, short), 200, 'Second session can log in');
  await assert.rejects(sql`INSERT INTO administrators(id,username,password_hash) VALUES (2,'other','unused')`, error => error.code === '23514'); checks.push('Database enforces singleton administrator');
  const migration = await readFile('db/migrations/0002_black_infant_terrible.sql', 'utf8');
  await assert.rejects(sql.begin(async tx => {
    await tx`ALTER TABLE administrators DROP CONSTRAINT administrators_singleton`;
    await tx`INSERT INTO administrators(id,username,password_hash) VALUES (2,'extra','unused')`;
    await tx.unsafe(migration.split('--> statement-breakpoint')[0]);
  }), /Extra administrator/);
  checks.push('Migration stops on extra accounts without deleting data');
  await status(await login(a, ''), 401, 'Empty login password rejected');
  for (let i = 0; i < 3; i++) await status(await login(a, 'incorrect'), 401, 'Failed login counted');
  await status(await login(a, short), 200, 'Correct password after four failures works');
  assert.equal(Number((await sql`SELECT count(*) AS n FROM login_limits`)[0].n), 0); checks.push('Successful login clears failures');
  for (let i = 0; i < 6; i++) assert.equal((await login(a, short)).status(), 200);
  assert.equal(Number((await sql`SELECT count(*) AS n FROM login_limits`)[0].n), 0); checks.push('Successful logins consume no failure allowance');
  const attempts = await Promise.all(Array.from({ length: 8 }, () => login(a, 'incorrect')));
  assert.equal(attempts.filter(r => r.status() === 401).length, 5);
  assert.equal(attempts.filter(r => r.status() === 429).length, 3); checks.push('Concurrent failures capped at five');
  await status(await login(a, short, username, { 'X-Forwarded-For': '203.0.113.1', 'X-Real-IP': '203.0.113.2' }), 429, 'Spoofed forwarding headers cannot bypass local limit');
  await status(await login(a, 'incorrect', 'different-account'), 401, 'Different submitted accounts have separate counters');
  await sql`UPDATE login_limits SET reset_at = now() - interval '1 second'`;
  await status(await login(a, short), 200, 'Expired failure window recovers');
  for (const route of ['/api/admin/password', '/api/admin/logout-all']) {
    await status(await anon.post(route, { headers, data: { currentPassword: short, newPassword: 'b', confirmPassword: 'b' } }), 401, 'Anonymous account operation rejected');
    await status(await a.post(route, { headers: { Origin: 'https://evil.invalid' }, data: {} }), 403, 'Cross-origin account operation rejected');
  }
  await status(await a.post('/api/admin/password', { headers, data: { currentPassword: short, newPassword: '', confirmPassword: '' } }), 400, 'Empty new password rejected');
  await status(await a.post('/api/admin/password', { headers, data: { currentPassword: short, newPassword: 'b', confirmPassword: 'c' } }), 400, 'Password confirmation checked');
  await status(await a.post('/api/admin/password', { headers, data: { currentPassword: 'wrong', newPassword: 'b', confirmPassword: 'b' } }), 401, 'Current password required');
  await status(await a.post('/api/admin/password', { headers, data: { currentPassword: short, newPassword: spaced, confirmPassword: spaced } }), 200, 'Password update preserves spaces');
  await denied(a); await denied(b);
  await status(await login(a, short), 401, 'Old password no longer logs in');
  await status(await login(a, spaced.trim()), 401, 'Trimmed password does not match');
  await status(await login(a, spaced), 200, 'Exact spaced password logs in');
  await status(await login(b, spaced), 200, 'Second browser can log in with new password');
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ baseURL, storageState: await a.storageState(), viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/admin'); await page.getByRole('link', { name: '账号安全' }).click();
  await expect(page.getByRole('heading', { name: '账号安全' })).toBeVisible();
  assert(await page.locator('input[type=password]').evaluateAll(inputs => inputs.every(input => input.minLength === -1 && input.maxLength === -1))); checks.push('Password form has no length constraints');
  await mkdir('outputs/auth-qa', { recursive: true });
  await page.screenshot({ path: 'outputs/auth-qa/security-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'outputs/auth-qa/security-mobile.png', fullPage: true });
  await page.getByLabel('当前密码', { exact: true }).fill(spaced);
  await page.getByLabel('新密码', { exact: true }).fill(short);
  await page.getByLabel('确认新密码', { exact: true }).fill(short);
  await page.getByRole('button', { name: '保存新密码并重新登录' }).click();
  await page.waitForURL('**/admin/login'); checks.push('Browser can change to a single-character password');
  await denied(a); await denied(b);
  await page.getByLabel('账号', { exact: true }).fill(username); await page.getByLabel('密码', { exact: true }).fill(short);
  await page.getByRole('button', { name: '登录写作台' }).click(); await page.waitForURL('**/admin');
  await login(b, short);
  await page.getByRole('link', { name: '账号安全' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '退出所有设备' }).click();
  await page.waitForURL('**/admin/login'); await denied(b);
  await status(await context.request.post('/api/admin/posts', { headers }), 401, 'Logout-all also revokes current browser');
  assert.deepEqual(errors, []); checks.push('Security page has no browser runtime errors');
  await login(a, short);
  const long = 'x'.repeat(512);
  await status(await a.post('/api/admin/password', { headers, data: { currentPassword: short, newPassword: long, confirmPassword: long } }), 200, 'Password longer than old 256-character cap accepted');
  await status(await login(a, long), 200, 'Long password login accepted');
  await setAdministrator(sql, username, ' ');
  await denied(a);
  await status(await login(a, ' '), 200, 'Initializer preserves space-only nonempty password');
  await status(await a.post('/api/admin/login', { headers: { ...headers, 'Content-Type': 'application/json' }, data: JSON.stringify({ username, password: 'x'.repeat(2_000_001) }) }), 413, 'General request size limit retained');
  await writeFile('outputs/auth-qa/results.json', JSON.stringify({ checks, browserErrors: errors }, null, 2));
  console.log(`PASS: ${checks.length} authentication checks`);
} finally {
  await browser?.close(); await a.dispose(); await b.dispose(); await anon.dispose();
  await sql`DELETE FROM admin_sessions`; await sql`DELETE FROM login_limits`; await sql`DELETE FROM administrators`; await sql.end();
}
