'use client';

import { useEffect, useRef } from 'react';
import ImageExtension from '@tiptap/extension-image';
import {
  NodeViewWrapper,
  ReactNodeViewRenderer,
  type ReactNodeViewProps,
} from '@tiptap/react';

export const FOCUS_IMAGE_CAPTION_EVENT = 'jiuheng:focus-image-caption';

function CaptionedImageView({
  node,
  updateAttributes,
  editor,
  getPos,
  selected,
}: ReactNodeViewProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const src = String(node.attrs.src ?? '');

  useEffect(() => {
    const focusCaption = (event: Event) => {
      if ((event as CustomEvent<string>).detail === src)
        inputRef.current?.focus();
    };
    window.addEventListener(FOCUS_IMAGE_CAPTION_EVENT, focusCaption);
    return () =>
      window.removeEventListener(FOCUS_IMAGE_CAPTION_EVENT, focusCaption);
  }, [src]);

  function finishCaption() {
    const position = getPos();
    if (typeof position !== 'number') return;
    const insertAt = position + node.nodeSize;
    editor
      .chain()
      .insertContentAt(insertAt, { type: 'paragraph' })
      .focus(insertAt + 1)
      .run();
  }

  return (
    <NodeViewWrapper
      as="figure"
      className={`editor-image${selected ? ' is-selected' : ''}`}
      data-image-src={src}
    >
      {/* The URL is generated by the authenticated asset route, not user HTML. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={src} alt={String(node.attrs.alt ?? '')} draggable={false} />
      <input
        ref={inputRef}
        className="editor-image-caption"
        aria-label="图片说明"
        value={String(node.attrs.alt ?? '')}
        maxLength={240}
        placeholder="添加图片说明（可选）"
        onChange={(event) => updateAttributes({ alt: event.target.value })}
        onKeyDown={(event) => {
          if (event.key === 'Enter') {
            event.preventDefault();
            finishCaption();
          }
          if (event.key === 'Escape') {
            event.preventDefault();
            const position = getPos();
            if (typeof position === 'number')
              editor.chain().setNodeSelection(position).focus().run();
          }
        }}
      />
    </NodeViewWrapper>
  );
}

export const CaptionedImage = ImageExtension.extend({
  addNodeView() {
    return ReactNodeViewRenderer(CaptionedImageView);
  },
}).configure({ allowBase64: false });
